name: "action-bump-uses"

author: "ryohidaka"

description: "GitHub Actions to update the version of the `uses` documented in the README."

branding:
  color: green
  icon: send

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set GitHub Path
      run: echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
      shell: bash
