name: "Bump Uses"

author: "ryohidaka"

description: "GitHub Actions to update the version of the `uses` documented in the README."

branding:
  color: blue
  icon: refresh-cw

inputs:
  # commit options
  commit-user-name:
    required: false
    default: "GitHub Actions"
    description: "Commit username. Defaults to 'GitHub Actions'."

  commit-user-email:
    required: false
    default: "actions@github.com"
    description: "Commit email. Defaults to 'actions@github.com'."

  commit-message:
    required: false
    default: "chore: Bump uses version"
    description: "Commit message. Defaults to 'chore: Bump uses version'."

  dry-run:
    description: "If true, the commit and push steps will be skipped."
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set GitHub Path
      run: echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
      shell: bash

    - name: Get latest release version
      run: |
        LATEST_VERSION=$($GITHUB_ACTION_PATH/scripts/get-version.sh "${{ github.repository }}")
        if [ -z "$LATEST_VERSION" ]; then
          echo "No new version available, skipping update."
          exit 0
        fi
        echo "RELEASE_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
      shell: bash

    - name: Update README.md with release version
      if: env.RELEASE_VERSION != ''
      run: |
        $GITHUB_ACTION_PATH/scripts/update-readme.sh "${{ github.repository }}" "$RELEASE_VERSION"
      shell: bash
      env:
        RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

    - name: Commit and Push
      if: env.RELEASE_VERSION != ''
      uses: ryohidaka/action-commit-push@v0.3.0
      with:
        files: "README.md"
        commit-user-name: "${{ inputs.commit-user-name }}"
        commit-user-email: "${{ inputs.commit-user-email }}"
        commit-message: "${{ inputs.commit-message }}"
        dry-run: ${{ inputs.dry-run }}
